language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE SCHEMA test_teacherspet;'

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
