language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE SCHEMA test_teacherspet;'
  - mysql test_teacherspet < teachersPetDatabaseSchema.sql

script:
  - ./gradlew test -i
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
